module.exports = {
    Ping: require('./ping'),
    EightBall: require('./8ball'),
    About: require('./about'),
    Fortune: require('./fortune'),
    AllRoles: require('./allroles'),
    Ban: require('./ban'),
    Kick: require('./kick'),
    Yell: require('./yell'),
    Poll: require('./poll'),
    Help: require('./help'),
    BotInvite: require('./botinvite'),
    Calculate: require('./calc'),
    Chngelog: require('./changelog'),
    Instant: require('./inst'),
    Echo: require('./echo'),
    Face: require('./face'),
    LoveCalculate: require('./lovecalc'),
    Question: require('./qu'),
    Rate: require('./rate'),
    Roll: require('./roll'),
    Slow: require('./slow'),
    Stop: require('./stop'),
    Tile: require('./tile'),
    WikiHow: require('./wh'),
    Who: require('./who'),
    Meme: require('./meme'),
};