module.exports = {
	name: 'wh',
	help: {
		"usage": "wh",
		"desc": "Gives you a random weird wikiHow article"
	},
	cool: 3600,
	execute(msg) {
		let articles = ["How to Avoid Being Affected by Insulting Commentary", "How to Walk Across the Brooklyn Bridge", "How to Chat",
		"How to Get Rid of the \'deja Vu\' Feeling", "How to Remove Blood from Hardwood Floors", "How to Befriend a Horse", "How to Do Variations of the Powerslam", "How to Go to Bed After Watching a Horror Movie", "How to Be a Contestant on The Price is Right", "How to Play Laser Tag", "How to Compete with Other Lemonade Stands", "How to Make a Wolverine Costume",
		"How to Seduce a Gemini", "How to Meet Donald Trump",
		"How to Tell Your Boyfriend He Needs to See a Dentist",
		"How to Become More Masculine when Feminine",
		"How to Handle a Child\'s Meltdown at the Store",
		"How to Make a Kid\'s Party Fun for Adults",
		"How to Convince your Pet Rock to Get Married", "How to Chew Gum", "How to Cope with a Fear of Tin Foil", "How to Take a Shower", "How to Take a Normal Shower", "How to Take a Shower Smoothly", "How to Be a Mystic",
		"How to Deal With Unruly Guests at Your Wedding", "How to Shoot Like Kevin Durant",
		"How to Have a Pet Cow", "How to Talk Loudly",
		"How to Join the US Secret Service", "How to Act Like You\'re Possessed", "How to Walk", "How to High Five", "How to Read a Book", "How to Make Ice Cubes with an Ice Tray", "How to Apologize to a Cat",
		"How to Sneak Your Cat Into Work", "How to Appreciate Death Metal",
		"How to Make Toast", "How to Know if You Are Drunk", "How to Rip Paper",
		"How to Be Random", "How to Convince Your Parents to Let You Buy a Nice Diary",
		"How to Prevent or Survive a Monkey Attack", "How to Safely Swim with Piranhas", "How to Dance at a Rave", "How to Survive an Encounter with an Ostrich", "How to Be Goth", "How to Be Awkward",
		"How to Cast a Love Spell", "How to Avoid Laughing at Obese Girls", "How to Calculate Pi by Throwing Frozen Hot Dogs",
		"How to Pronounce Meme", "How to Impress Middle School Boys with your Family Guy Knowledge", "How to be Okay with Having a Communist Friend", "How to Become a Bounty Hunter", "How to Mind Your Own Business",
		"How to Manipulate People", "How to Survive After a Shipwreck", "How to Work in Area 51",
		"How to Avoid Griefers in Your House in Minecraft Pocket Edition Lite", "How to Get Other Guys to Stop Staring at Your Pretty Wife",
		"How to Get Your Adult Children to Move Out", "How to Spy on People",
		"How to Use a Webcam to Spy on People", "How to Download Fortnite on Chromebook", "How to Play Papa\'s Pancakeria", "How to Play Papa\'s Wingeria", "How to Make Awesome Burgers on Papa\'s Burgeria", "How to Get 0 Points in Papa\'s Hot Doggeria",
		"How to Play Papa\'s Scooperia on PC or Mac", "How to Hide from a Murderer", "How to Speak Gibberish", "How to Make a Fist", "How to Draw Adolf Hitler", "How to Be a Cowboy",
		"How to Do Spiritual Warfare", "How to Make Fossils", "How to Resolve an Identity Crisis", "How to Install Car Mods in Grand Theft Auto San Andreas", "How to Feel Comfortable in a Swimsuit", "How to Use wikiHow",
		"How to Create your Own Country", "How to Color Chickens", "How to Pretend you are a Werewolf", "How to Get Evidence of Santa Claus", "How to Enjoy the Taste of Water", "How to Pretend you Have Ice Powers", "How to Look Like you are on Drugs", "How to Breathe",
		"How to Act Like a Mermaid at School", "How to Emulate Hannah Montana", "How to Make a Meme", "How to Plan Your Own Funeral", "How to Eat Carrots", "How to Be an Atheist", "How to Start a Preschool", "How to Be Strange", "How to Tell Someone at Work that They Smell Bad",
		"How to Make your own Holy Water", "How to Spot Fake Gucci Glasses", "How to Spot a Fake Gucci Belt",
		"How to Spot a Fake Gucci Bag", "How to Dress Like a Gangsta", "How to Take Care of your Carnival Goldfish", "How to Convince Your Mom to Say Yes",
		"How to Make a Peanut Butter and Jelly Sandwich", "How to Make a Website Using Google Sites",
		"How to Skin a Raccoon", "How to Make a Secret Hideout in your Closet", "How to Sneak Around", "How to Make Beats Like Kanye West",
		"How to Act Shy at School so People will Think You are Cool and You will Be the Best", "How to Appreciate Anime", "How to Keep Your Thoughts Inside Your Head", "How to Go to McDonalds",
		"How to Win an Argument When You Know You are Wrong", "How to Borrow Money From Your Parents Without Permission", "How to Take a Shower With a Lemon", "How to Take a Shower if You Don’t Want to",
		"How to Eat Pizza", "How to Tell Left from Right", "How to Accept that Your Computer is Slow", "How to Feel a Guy’s Muscle Without Looking Gay", "How to Remove Your Own Dental Work", "How to Make a Hamburger ",
		"How to Choose Between Paperback and Hardback Books", "How to Wear Ugg Boots",
		"How to Play Human Tic Tac Toe", "How to Make Your Own Wrestling Ring ", "How to Grow a Quality Medical Marijuana ", "How to Overcome Chatting Addiction ", "How to Make an Anime",
		"How to Build a Big Chest ", "How to Keep a Pet Fly", "How to Get Your Dog Paid TV Appearances", "How to Develop Personality", "How to Remove Blood Stains from Carpet ", "The Best Ways to Test for Asbestos",
		"How to Get a Tough Girl to Like You ", "How to Wear a Beanie ", "How to Stop Peeling Lips",
		"How to Survive Going Through Pregnancy Alone As a Teen", "How to Tape a Broken Pinky Toe",
		"How to Love Your Stuffed Animal ", "How to Hold a Hermit Crab", "How to Be a Popular Tomboy ", "How to Preserve a Severed Limb for Reattachment",
		"How to Cope With a Flirtatious Co Worker", "How to Stop Mouth Breathing",
		"How to Handle Smart People", "How to Spot Signs of Disease in Doves", "How to Get Slime Out of Hair", "How to Cook With Coca Cola", "How to Widen Your Logic and Knowledge",
		"How to Emulate Lana Del Rey", "How to Deal With Relatives You Hate ",
		"How to Meditate in a Labyrinth ", "How to Dress Emo in the Summer",
		"How to Take Group Photos", "How to Love a Married Man", "How to Clean Straw Hats",
		"How to Ask a Girl out in High School if You Are Shy and She Does Not Know You", "How to Take Care of Your Furby ",
		"How to Identify Different Types of Forklifts", "How to Make Fry Bread ", "How to Tell if You Have a Migraine", "How to Accept that Your Crush Doesn\'t Like You",
		"How to Purchase a Gas Station ", "How to Talk Faster ",
		"How to Massage Yourself", "How to Explain Photosynthesis", "How to Disagree With Your Doctor", "How to Use a Gun (Women) ",
		"How to Deal With a Cursing Person", "How to Talk Loudly ", "How to Deal With Bad News",
		"How to Avoid Going Over an Essay Word Limit",
		"How to Tell if Your Cat Is Blind", "How to Catch a Fly With Your Hands", "How to Play the Hunger Games Outdoor Game", "How to Get a Guy You Don\'t Like to Stop Liking You ", "How to Become More Intelligent Than You Are Now",
		"How to Be a Computer Genius", "How to Avoid Being an Obsessive Girlfriend",
		"How to Wash Eyes With Water", "How to Kill Herobrine in Minecraft ", "How to Sell Candy in School", "How to Pick Good Minecraft Servers",
		"How to Encourage Your Baby to Roll", "How to Avoid Skin Problems at Work ", "How to Compliment a Woman ",
		"How to Get Rid of Yellowness in Gray Hair", "How to Recognize Signs of Dyslexia", "How to Play SkyBlock in Minecraft", "How to Keep Discus", "How to Spot a Fake Coach Bag",
		"How to Make Colored Ice ", "How to Stop Finishing Other People\'s Sentences",
		"How to Become a Model if You\'re Short", "How to Find a Cave in Minecraft",
		"How to Get Your Dog to Stop Playing Fetch With You", "How to Determine Correct Primary Colors ",
		"How to Confront a Friend Whose Child Bullies Your Child", "How to Stop Kittens from Crying ",
		"How to Write a Great Christian Song ", "How to Train or Help a Puppy Stop Crying when Locked up or Outside",
		"How to Build an Underground House", "How to Get 360 Waves ",
		"How to Enjoy Your Holiday Alone", "How to Have a Pleasant Facial Expression",
		"How to Be a Modern Hippie", "How to Use Uber with an International Phone",
		"How to Get a Celebrity to Follow You on Twitter", "How to Escape Zombies in Minecraft PE",
		"How to Feed a Baby Pigeon ", "How to Ripen a Cantaloupe ", "How to Resell Dollar Store Goods ", "How to Get over Your Addiction to Mountain Dew", "How to Talk So Teens Will Listen", "How to Win a Nerf War ",
		"How to Cope when Your Teenager Falls in Love", "How to Help a Pecked Chicken with a Wound", "How to Date a Capricorn Man ", "How to Install Adobe Flash Player",
		"How to Dye Fabric With Tea ", "How to Stop Being Manipulative", "How to Help a Dog That May Have Been Poisoned",
		"How to Pretend You Are Not Sick", "How to Draw Squidward from SpongeBob SquarePants", "How to Stop Being Superstitious ",
		"How to Read an Aura ", "How to Get 8 Pack Abs",
		"How to Act Like a Rich Girl ", "How to Develop Telepathy ", "How to Beat Level 77 in Candy Crush Saga", "How to Understand Cockatiel Gestures ", "How to Act Like Jim Halpert ",
		"How to Feel Lucky", "How to Turn On Headlights ", "How to Eat Almonds",
		"How to Become a Psychic Medium", "How to Be Sassy ",
		"How to Quit Smoking Weed", "How to Not Pick a Scab ",
		"How to Be a Kid Actor ", "How to Look Sick with Makeup ",
		"How to Date a Millionaire ", "How to Contact Rihanna", "How to Give Your Hermit Crab a Bath ",
		"How to Travel to Antarctica", "How to Make an Atheist and Theist Relationship Work", "How to Manage a Nerf Team ",
		"How to Do the Russian Squat‐and‐Kick Dance", "How to Do a Scorpion in Cheerleading", "How to Stop Being Mean to People",
		"How to Punch Harder", "How to Make a Bucket Hat ", "How to Remove Eyelash Glue", "How to Communicate with Your Cat", "How to Use a Ruler", "How to Drop Items in Oblivion ",
		"How to Stop Fantasizing", "How to Not Pick a Scab ", "How to Do Toes to Bar ",
		"How to Tell Your Boss You\'ve Made a Major Mistake", "How to Make a Fireball",
		"How to Change Your Name on wikiHow", "How to Make a Calm Down Corner (9 15 Years Old)", "How to Make a Ninja Impact Smoke Bomb ", "How to Be Macho", "How to Use the Ouija Board Safely ", "How to Be Tolerant to People\'s Opinions ", "How to Make a Beaded Lizard",
		"How to Talk Like a Stereotypical New Yorker", "How to Convince Others That You Are Not Shy",
		"How to Hide a Big Nose", "How to Sell Firewood", "How to Be Cunning ", "How to Treat Diarrhea in Doves",
		"How to Take a Leap of Faith ", "How to Eat Like an Olympian ", "How to Win a Game of Clue Without Technically Cheating", "How to Build a Big Sandcastle ",
		"How to Say a Novena to St. Therese the Little Flower", "How to Make a Bouncy Egg ", "How to Show a Girl That You Care (for Guys)",
		"How to Answer the Question “Who Are You”", "How to Melt Nutella",
		"How to Show Chickens ", "How to Protect Yourself After Unknowingly Buying Stolen Property",
		"How to Use Bodywash ", "How to Blow Dry Your Hair Without Getting Damaged", "How to Be Stubborn ", "How to Become Pope ",
		"How to Be a Christian Teen Dealing With Non Christian Friends", "How to Become a Clown", "How to Find a Snail ", "How to Avoid \'New Tank\' Syndrome ",
		"How to Throw a Progressive Dinner Party ", "How to Remove Blood Stains from Wood",
		"How to Melt Coconut Oil", "How to Care for a Toy Poodle",
		"How to Protest Part of Your School\'s Student Code", "How to Sneak a Pad or Tampon to the Bathroom at School",
		"How to Stop Absorbing Other People\'s Emotions", "How to Make Apple Jello Shots"
	]
	let artchoice = articles[Math.abs(Math.round(Math.random() * articles.length) - 1)];
	msg.channel.send(artchoice).catch("console.error");
},
};